const responseObj = {
  "hey": "Hey! What's up?",
  "how are you": "I am good, thanks for asking!",
  "what's your name?": "I am a friendly chatbot here to help you!",
  "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
  "what is the weather like?": "I'm not sure, but you can check your local weather report.",
  "what can you do?": "I can chat with you, tell jokes, provide information, and much more!",
  "who created you?": "I was created by a team of developers to assist you.",
  "what is the capital of India?": "The capital of India is New Delhi.",
  "bye": "Goodbye! Have a great day!",
  "thank you": "You're welcome! If you have any more questions, feel free to ask.",
  "what is your favorite color?": "As a chatbot, I don't have a favorite color, but I think all colors are beautiful!",
  "how old are you?": "I don't have an age, but I'm here to assist you anytime!",
  "what is the meaning of life?": "The meaning of life is a deeply philosophical question. What do you think it is?",
  "can you help me with my homework?": "Sure! I can try to help. What subject are you working on?",
  "what is your favorite movie?": "I don't watch movies, but I've heard that 'The Matrix' is a great one!",
  "do you like music?": "I don't listen to music, but I'd love to hear about your favorite songs!",
  "what is your purpose?": "My purpose is to assist you with any questions or tasks you might have.",
  "where are you from?": "I exist in the digital world, created by developers.",
  "do you have any pets?": "I don't have pets, but I think animals are wonderful!",
  "can you dance?": "I can't dance, but I can certainly chat with you about dancing!",
  "what is artificial intelligence?": "Artificial Intelligence is the simulation of human intelligence in machines that are programmed to think and learn.",
  "tell me a fun fact": "Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible!",
  "what is the time?": "I don't have access to real-time data, but you can check the current time on your device.",
  "can you speak other languages?": "I can understand and respond in multiple languages. Try asking me something in another language!",
  "what is your favorite food?": "I don't eat food, but I can tell you about many delicious dishes!",
  "how do you work?": "I work by processing your input and matching it with pre-defined responses in my database.",
  "can you tell me a story?": "Once upon a time, in a land far, far away, there was a magical chatbot that loved to help people...",
  "how to start coding": "First you have to choose at least a language, which is like a c, c++, java, python etc.",
  "which language should we prefer": "According to your choice, but python is not preferable for DSA, but you can choose this as your first language.",
  "what is computer" : "A computer is an electronic device that processes data and performs tasks according to a set of instructions called a program. It can store, retrieve, and manipulate information to carry out a wide variety of functions, from simple calculations to complex operations.",
  };